name: 'Steam - Deploy'
author: Webber Takken <webber@takken.io>
description: 'Deploy game builds to Steam using the SteamSDK.'
inputs:
  username:
    required: true
    default: ''
    description: 'The username of your builder account.'
  password:
    required: true
    default: ''
    description: 'The password of your builder account.'
  mfaCode:
    required: true
    default: ''
    description: 'The MFA code emailed to your account.'
  configVdf:
    required: true
    default: ''
    description: 'The contents of the file at STEAM_HOME/config/config.vdf'
  ssfnFileName:
    required: true
    default: ''
    description: 'basename of ls STEAM_HOME/ssfn.'
  ssfnFileContents:
    required: true
    default: ''
    description: 'The contents of the file at STEAM_HOME/ssfnFileName.'
  appId:
    required: true
    default: ''
    description: 'The app id within steam partner network.'
  buildDescription:
    required: false
    description: 'Description for this build.'
  rootPath:
    required: false
    description: 'The root path to your builds. This is the base of which depots will search your files.'
  depot1Path:
    required: false
    description: 'The path to depot1.'
  depot2Path:
    required: false
    description: 'The path to depot2.'
  depot3Path:
    required: false
    description: 'The path to depot3.'
  depot4Path:
    required: false
    description: 'The path to depot4.'
  depot5Path:
    required: false
    description: 'The path to depot5.'
  depot6Path:
    required: false
    description: 'The path to depot6.'
  depot7Path:
    required: false
    description: 'The path to depot7.'
  depot8Path:
    required: false
    description: 'The path to depot8.'
  depot9Path:
    required: false
    description: 'The path to depot9.'
  releaseBranch:
    required: false
    description: 'The branch within steam that this build will be automatically put live on.'
outputs: {}
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: "composite"
  steps:
    - id: steamsetup
      uses: CyberAndrii/setup-steamcmd@v1.1.1
    - id: deploy
      shell: bash
      run: |
        export STEAMCMDDIR=${{ steps.steamsetup.outputs.directory }}
        export username=${{ inputs.username }}
        export password=${{ inputs.password }}
        export mfaCode=${{ inputs.mfaCode }}
        export configVdf=${{ inputs.configVdf }}
        export ssfnFileName=${{ inputs.ssfnFileName }}
        export ssfnFileContents=${{ inputs.ssfnFileContents }}
        export appId=${{ inputs.appId }}
        export buildDescription=${{ inputs.buildDescription }}
        export rootPath=${{ inputs.rootPath }}
        export depot1Path=${{ inputs.depot1Path }}
        export depot2Path=${{ inputs.depot2Path }}
        export depot3Path=${{ inputs.depot3Path }}
        export depot4Path=${{ inputs.depot4Path }}
        export depot5Path=${{ inputs.depot5Path }}
        export depot6Path=${{ inputs.depot6Path }}
        export depot7Path=${{ inputs.depot7Path }}
        export depot8Path=${{ inputs.depot8Path }}
        export depot9Path=${{ inputs.depot9Path }}
        export releaseBranch=${{ inputs.releaseBranch }}
        chmod +x ${{ github.action_path }}/action/2_show_configuration.sh
        chmod +x ${{ github.action_path }}/action/3_generate_depot_manifests.sh
        chmod +x ${{ github.action_path }}/action/4_generate_app_manifest.sh
        chmod +x ${{ github.action_path }}/action/5_copy_steamguard_files.sh
        chmod +x ${{ github.action_path }}/action/6_execute_steamcmd.sh
        ${{ github.action_path }}/action/2_show_configuration.sh
        ${{ github.action_path }}/action/3_generate_depot_manifests.sh
        ${{ github.action_path }}/action/4_generate_app_manifest.sh
        ${{ github.action_path }}/action/5_copy_steamguard_files.sh
        ${{ github.action_path }}/action/6_execute_steamcmd.sh
        echo "Exporting STEAM_CONFIG_VDF..."
        export STEAM_CONFIG_VDF="$(cat /home/runner/Steam/config/config.vdf)"
        echo "::set-output name=STEAM_CONFIG_VDF::$STEAM_CONFIG_VDF"
        echo "Exporting STEAM_SSFN_FILE_NAME..."
        export STEAM_SSFN_FILE_NAME="$(basename $(ls /home/runner/Steam/ssfn*))"
        echo "::set-output name=STEAM_SSFN_FILE_NAME::$STEAM_SSFN_FILE_NAME"
        echo "Exporting STEAM_SSFN_FILE_CONTENTS..."
        export STEAM_SSFN_FILE_CONTENTS="$(cat /home/runner/Steam/$STEAM_SSFN_FILE_NAME | base64)"
        echo "::set-output name=STEAM_SSFN_FILE_CONTENTS::$STEAM_SSFN_FILE_CONTENTS"
        echo "Exported secrets!"
    - uses: gliech/create-github-secret-action@v1
      with:
        name: STEAM_CONFIG_VDF
        value: ${{ steps.deploy.outputs.STEAM_CONFIG_VDF }}
        pa_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: gliech/create-github-secret-action@v1
      with:
        name: STEAM_SSFN_FILE_NAME
        value: ${{ steps.deploy.outputs.STEAM_SSFN_FILE_NAME }}
        pa_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: gliech/create-github-secret-action@v1
      with:
        name: STEAM_SSFN_FILE_CONTENTS
        value: ${{ steps.deploy.outputs.STEAM_SSFN_FILE_CONTENTS }}
        pa_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
