name: 🚀

on:
  push: { branches: [main] }
  pull_request: {}
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment to Steam ☁
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p build/StandaloneWindows64
          mkdir -p build/StandaloneLinux64
          touch build/StandaloneWindows64/test.txt
          touch build/StandaloneLinux64/test.txt
          chmod -R 777 build
      - uses: ./
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          mfaCode: ${{ secrets.STEAM_MFA_CODE }}
          personalAccessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFilePath: ${{ secrets.STEAM_SSFN_FILE_PATH }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: 1234560
          buildDescription: v0.0.1
          rootPath: build
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneLinux64
          releaseBranch: prerelease
